name: Update and commit

on:
  workflow_dispatch:
  schedule:
  # once a day at  5:35, 11:35, 17:35 on JST
  - cron:  '35 20,2,8 * * *'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |- 
        sudo apt-get install -y --no-install-recommends libsqlite3-mod-spatialite
        pip install sqlite-utils
    - name: update dates.json and tiles
      run: |
        bash scripts/clone-data.sh
        bash scripts/make-dates-json.sh

        # only update the latest 2 days
        for day in $(jq -r '.[0:2][]' docs/tile/temperature/dates.json); do
          bash scripts/make-tile.sh $day
        done

    - name: Commit and push
      run: |-
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A

        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
